apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::907069229663:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NVKM6ZMQVL5J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::907069229663:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-07T06:30:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1564"
  uid: 055696e0-40b3-433e-b1b5-a5784b37fc7a
